"""initial

Revision ID: 3fbfaebe1abb
Revises: 
Create Date: 2023-12-16 22:35:05.678797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbfaebe1abb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('memberId', sa.String(), nullable=False),
    sa.Column('memberName', sa.String(), nullable=True),
    sa.Column('memberEmail', sa.String(), nullable=True),
    sa.Column('memberAge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('memberId')
    )
    op.execute("UPDATE members Set memberAge = memberAge + 1")    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
